apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}-mysql-svc
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - name: {{ .Values.db.service.name }}
      port: {{ .Values.db.service.port }}
      targetPort: 3306
      protocol: TCP
  selector:
    {{- include "helloworld.selectorLabels" . | nindent 4 }}
    tier: db

